### PR TITLE
README fix Hex.pm badge link

### PR DESCRIPTION
**Pull request by szTheory**

### CODE REVIEW

**Comment by mandarvaze** [comment]
@szTheory Can you explain what is exactly fixed ? Since the this is one long single line - I am unable to figure out the difference.

May be copy **just the relevant change**, and explain it here ?

**Comment by mandarvaze** [comment]
@ashish173 @pkrawat1 I think the link needs to point to `https://hex.pm/packages/gringotts/1.1.1-rc` instead of generic `https://hex.pm/packages/gringotts`, since the image text shows `v1.1.1-rc`

**Comment by szTheory** [comment]
I think it just pulls the latest entry from the Versions section on the Hex.pm page

**Comment by mandarvaze** [comment]
@szTheory The latest release is 1.1.0 (and 1.1.1 being rc is not pulled unless explicitly asked for)

But I think what you are suggesting makes sense, otherwise with each released README will need to be updated.

**Comment by mandarvaze** [comment]
@szTheory Thanks for your contribution. This PR is finally merged :)

**Pull request merged**
